modLoader = "javafml"
loaderVersion = "[${forge},)"
license = "GPL-3.0"
issueTrackerURL = "https://invalid.change.me"

[[mods]]
modId = "template"
version = "${version}"
displayName = "template"
logoFile = "icon.png"
authors = "rdh"
description = '''
Example mod description.
'''

[[dependencies.template]]
modId = "neoforge"
type = "required"
versionRange = "[${neo},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.template]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft},)"
ordering = "NONE"
side = "BOTH"
